package cloud.worx;

public enum States {
    BAYERN,
    BADEN_WÜRTTEMBERG,
    BERLIN,
    BRANDENBURG,
    BREMEN,
    HAMBURG,
    HESSEN,
    MECKLENBURG_VORPOMMERN,
    NIEDERSACHSEN,
    NORDRHEIN_WESTFALEN,
    RHEINLAND_PFALZ,
    SAARLAND,
    SACHSEN,
    SACHEN_ANHALT,
    SCHLESWIG_HOLSTEIN,
    THÜRINGEN
}
